export const ENFYRA_MACRO_COMPLETIONS = [
  { label: '@CACHE', type: 'variable', detail: '$ctx.$cache' },
  { label: '@REPOS', type: 'variable', detail: '$ctx.$repos' },
  { label: '@HELPERS', type: 'variable', detail: '$ctx.$helpers' },
  { label: '@FETCH', type: 'function', detail: '$ctx.$helpers.$fetch' },
  { label: '@LOGS', type: 'function', detail: '$ctx.$logs' },
  { label: '@BODY', type: 'variable', detail: '$ctx.$body' },
  { label: '@DATA', type: 'variable', detail: '$ctx.$data' },
  { label: '@PARAMS', type: 'variable', detail: '$ctx.$params' },
  { label: '@QUERY', type: 'variable', detail: '$ctx.$query' },
  { label: '@USER', type: 'variable', detail: '$ctx.$user' },
  { label: '@REQ', type: 'variable', detail: '$ctx.$req' },
  { label: '@RES', type: 'variable', detail: '$ctx.$res' },
  { label: '@SHARE', type: 'variable', detail: '$ctx.$share' },
  { label: '@API', type: 'variable', detail: '$ctx.$api' },
  { label: '@UPLOADED_FILE', type: 'variable', detail: '$ctx.$uploadedFile' },
  { label: '@PKGS', type: 'variable', detail: '$ctx.$pkgs' },
  { label: '@SOCKET', type: 'variable', detail: '$ctx.$socket' },
  { label: '@TRIGGER', type: 'function', detail: '$ctx.$trigger' },
  { label: '@FLOW', type: 'variable', detail: '$ctx.$flow' },
  { label: '@FLOW_PAYLOAD', type: 'variable', detail: '$ctx.$flow.$payload' },
  { label: '@FLOW_LAST', type: 'variable', detail: '$ctx.$flow.$last' },
  { label: '@FLOW_META', type: 'variable', detail: '$ctx.$flow.$meta' },
  { label: '@ERROR', type: 'variable', detail: '$ctx.$error' },
  { label: '@STATUS', type: 'variable', detail: '$ctx.$statusCode' },
  { label: '@THROW', type: 'function', detail: '$ctx.$throw' },
  { label: '@THROW400', type: 'function', detail: "$ctx.$throw['400']" },
  { label: '@THROW401', type: 'function', detail: "$ctx.$throw['401']" },
  { label: '@THROW403', type: 'function', detail: "$ctx.$throw['403']" },
  { label: '@THROW404', type: 'function', detail: "$ctx.$throw['404']" },
  { label: '@THROW409', type: 'function', detail: "$ctx.$throw['409']" },
  { label: '@THROW422', type: 'function', detail: "$ctx.$throw['422']" },
  { label: '@THROW429', type: 'function', detail: "$ctx.$throw['429']" },
  { label: '@THROW500', type: 'function', detail: "$ctx.$throw['500']" },
  { label: '@THROW503', type: 'function', detail: "$ctx.$throw['503']" },
];

export const ENFYRA_COMPLETIONS = ENFYRA_MACRO_COMPLETIONS;

export const ENFYRA_CTX_COMPLETIONS = [
  { label: '$ctx', type: 'variable', detail: 'Dynamic execution context' },
  { label: '$body', type: 'property', detail: 'Request body / flow payload body' },
  { label: '$data', type: 'property', detail: 'Response data or websocket payload' },
  { label: '$throw', type: 'property', detail: 'HTTP error helpers by status code' },
  { label: '$error', type: 'property', detail: 'Current error context' },
  { label: '$statusCode', type: 'property', detail: 'Response status code' },
  { label: '$logs', type: 'method', detail: 'Append execution logs' },
  { label: '$helpers', type: 'property', detail: 'Built-in helpers' },
  { label: '$cache', type: 'property', detail: 'Cache service' },
  { label: '$params', type: 'property', detail: 'Route params' },
  { label: '$query', type: 'property', detail: 'Parsed query params' },
  { label: '$user', type: 'property', detail: 'Current user' },
  { label: '$repos', type: 'property', detail: 'Repository registry' },
  { label: '$req', type: 'property', detail: 'Sanitized request object' },
  { label: '$res', type: 'property', detail: 'Express response in handlers' },
  { label: '$share', type: 'property', detail: 'Shared hook/handler state' },
  { label: '$api', type: 'property', detail: 'Request/response/error metadata' },
  { label: '$uploadedFile', type: 'property', detail: 'Uploaded file metadata' },
  { label: '$debug', type: 'property', detail: 'Debug trace context' },
  { label: '$socket', type: 'property', detail: 'WebSocket helpers' },
  { label: '$flow', type: 'property', detail: 'Flow payload, metadata, and step results' },
  { label: '$trigger', type: 'method', detail: 'Trigger another flow' },
];

export const ENFYRA_HELPER_COMPLETIONS = [
  { label: '$jwt', type: 'function', detail: '(payload, exp) => string' },
  { label: '$bcrypt', type: 'property', detail: '{ hash, compare }' },
  { label: 'autoSlug', type: 'function', detail: '(text) => string' },
  { label: '$rateLimit', type: 'property', detail: 'Rate limit helper' },
  { label: '$uploadFile', type: 'function', detail: '(options) => Promise<any>' },
  { label: '$updateFile', type: 'function', detail: '(fileId, options) => Promise<any>' },
  { label: '$deleteFile', type: 'function', detail: '(fileId) => Promise<any>' },
  { label: '$fetch', type: 'function', detail: 'Safe fetch helper' },
];

export const ENFYRA_CACHE_COMPLETIONS = [
  { label: 'acquire', type: 'method', detail: '(key, value, ttlMs)' },
  { label: 'release', type: 'method', detail: '(key, value)' },
  { label: 'get', type: 'method', detail: '(key)' },
  { label: 'set', type: 'method', detail: '(key, value, ttlMs?)' },
  { label: 'exists', type: 'method', detail: '(key, value)' },
  { label: 'deleteKey', type: 'method', detail: '(key)' },
  { label: 'setNoExpire', type: 'method', detail: '(key, value)' },
];

export const ENFYRA_SOCKET_COMPLETIONS = [
  { label: 'join', type: 'method', detail: '(room)' },
  { label: 'leave', type: 'method', detail: '(room)' },
  { label: 'reply', type: 'method', detail: '(event, data)' },
  { label: 'emitToUser', type: 'method', detail: '(userId, event, data)' },
  { label: 'emitToRoom', type: 'method', detail: '(room, event, data)' },
  { label: 'emitToGateway', type: 'method', detail: '(path, event, data)' },
  { label: 'broadcast', type: 'method', detail: '(event, data)' },
  { label: 'roomSize', type: 'method', detail: '(room)' },
  { label: 'disconnect', type: 'method', detail: '()' },
];

export const ENFYRA_THROW_COMPLETIONS = [
  { label: '400', type: 'function', detail: '(message)' },
  { label: '401', type: 'function', detail: '(message?)' },
  { label: '403', type: 'function', detail: '(message?)' },
  { label: '404', type: 'function', detail: '(resource, id?)' },
  { label: '409', type: 'function', detail: '(resource, field, value)' },
  { label: '422', type: 'function', detail: '(message, details?)' },
  { label: '429', type: 'function', detail: '(limit, window)' },
  { label: '500', type: 'function', detail: '(message, details?)' },
  { label: '503', type: 'function', detail: '(service)' },
];

export const ENFYRA_FLOW_COMPLETIONS = [
  { label: '$payload', type: 'property', detail: 'Input payload' },
  { label: '$last', type: 'property', detail: 'Last step result' },
  { label: '$meta', type: 'property', detail: 'Flow metadata' },
];

export const ENFYRA_METHOD_COMPLETIONS = [
  { label: 'find', type: 'method', detail: '({ filter, fields, limit, sort })' },
  { label: 'findOne', type: 'method', detail: '({ filter, fields })' },
  { label: 'create', type: 'method', detail: '({ data })' },
  { label: 'update', type: 'method', detail: '({ id, data })' },
  { label: 'delete', type: 'method', detail: '({ id })' },
  { label: 'count', type: 'method', detail: '({ filter })' },
  { label: 'aggregate', type: 'method', detail: '({ aggregate })' },
];

export const VUE_COMPLETIONS = [
  { label: 'ref', type: 'function', detail: 'Reactive reference' },
  { label: 'reactive', type: 'function', detail: 'Reactive object' },
  { label: 'computed', type: 'function', detail: 'Computed property' },
  { label: 'readonly', type: 'function', detail: 'Readonly proxy' },
  { label: 'shallowRef', type: 'function', detail: 'Shallow reactive ref' },
  { label: 'shallowReactive', type: 'function', detail: 'Shallow reactive object' },
  { label: 'watch', type: 'function', detail: 'Watch reactive source' },
  { label: 'watchEffect', type: 'function', detail: 'Auto-tracking effect' },
  { label: 'onMounted', type: 'function', detail: 'Lifecycle: mounted' },
  { label: 'onUnmounted', type: 'function', detail: 'Lifecycle: unmounted' },
  { label: 'onBeforeMount', type: 'function', detail: 'Lifecycle: before mount' },
  { label: 'onBeforeUnmount', type: 'function', detail: 'Lifecycle: before unmount' },
  { label: 'onUpdated', type: 'function', detail: 'Lifecycle: updated' },
  { label: 'nextTick', type: 'function', detail: 'Next DOM update' },
  { label: 'defineProps', type: 'function', detail: 'Declare props' },
  { label: 'defineEmits', type: 'function', detail: 'Declare emits' },
  { label: 'defineExpose', type: 'function', detail: 'Expose to parent' },
  { label: 'resolveComponent', type: 'function', detail: 'Resolve dynamic component' },
  { label: 'h', type: 'function', detail: 'Create VNode' },
  { label: 'toRef', type: 'function', detail: 'Property to ref' },
  { label: 'toRefs', type: 'function', detail: 'Object to refs' },
  { label: 'unref', type: 'function', detail: 'Unwrap ref value' },
  { label: 'isRef', type: 'function', detail: 'Check if ref' },
  { label: 'toRaw', type: 'function', detail: 'Get raw object' },
  { label: 'markRaw', type: 'function', detail: 'Mark non-reactive' },
  { label: 'useRoute', type: 'function', detail: 'Nuxt: current route' },
  { label: 'useRouter', type: 'function', detail: 'Nuxt: router instance' },
  { label: 'navigateTo', type: 'function', detail: 'Nuxt: navigate' },
  { label: 'useState', type: 'function', detail: 'Nuxt: shared state' },
  { label: 'useCookie', type: 'function', detail: 'Nuxt: cookie ref' },
  { label: 'useNuxtApp', type: 'function', detail: 'Nuxt: app instance' },
  { label: 'useRuntimeConfig', type: 'function', detail: 'Nuxt: runtime config' },
  { label: 'useFetch', type: 'function', detail: 'Nuxt: fetch data' },
  { label: 'useAsyncData', type: 'function', detail: 'Nuxt: async data' },
  { label: 'useLazyFetch', type: 'function', detail: 'Nuxt: lazy fetch' },
  { label: 'useHead', type: 'function', detail: 'Nuxt: head meta' },
  { label: 'useToast', type: 'function', detail: 'Nuxt UI: toast notifications' },
  { label: 'useApi', type: 'function', detail: 'Enfyra: API client { data, execute, error, pending }' },
  { label: 'useAuth', type: 'function', detail: 'Enfyra: { me, login, logout, isLoggedIn }' },
  { label: 'usePermissions', type: 'function', detail: 'Enfyra: { hasPermission, checkPermissionCondition }' },
  { label: 'useSchema', type: 'function', detail: 'Enfyra: { schemas, fetchSchema, definition, editableFields, generateEmptyForm }' },
  { label: 'useGlobalState', type: 'function', detail: 'Enfyra: { settings, storageConfigs, sidebarVisible }' },
  { label: 'useScreen', type: 'function', detail: 'Enfyra: { isMobile, isTablet, isDesktop, width, height }' },
  { label: 'useConfirm', type: 'function', detail: 'Enfyra: { confirm({ title, content }) }' },
  { label: 'useHeaderActionRegistry', type: 'function', detail: 'Enfyra: register header actions' },
  { label: 'useSubHeaderActionRegistry', type: 'function', detail: 'Enfyra: register sub-header actions' },
  { label: 'useMenuRegistry', type: 'function', detail: 'Enfyra: { menuItems, registerMenuItem }' },
  { label: 'useFilterQuery', type: 'function', detail: 'Enfyra: { buildQuery, createEmptyFilter }' },
  { label: 'useDatabase', type: 'function', detail: 'Enfyra: { getId, getIdFieldName }' },
  { label: 'useRoutes', type: 'function', detail: 'Enfyra: route management' },
  { label: 'useHighlight', type: 'function', detail: 'Enfyra: code highlighting' },
  { label: 'useMounted', type: 'function', detail: 'Enfyra: { isMounted }' },
];

export const VUE_COMPONENT_COMPLETIONS = [
  { label: 'EmptyState', type: 'class', detail: 'Common: empty state display' },
  { label: 'LoadingState', type: 'class', detail: 'Common: loading indicator' },
  { label: 'ErrorState', type: 'class', detail: 'Common: error display' },
  { label: 'PageHeader', type: 'class', detail: 'Common: page header' },
  { label: 'FormCard', type: 'class', detail: 'Common: form container' },
  { label: 'Modal', type: 'class', detail: 'Common: modal dialog' },
  { label: 'Drawer', type: 'class', detail: 'Common: slide drawer' },
  { label: 'DataTable', type: 'class', detail: 'Data: sortable table' },
  { label: 'DataTableLazy', type: 'class', detail: 'Data: lazy-loaded table' },
  { label: 'FormEditor', type: 'class', detail: 'Form: metadata-driven editor' },
  { label: 'FilterEditor', type: 'class', detail: 'Form: filter builder' },
  { label: 'FieldSelector', type: 'class', detail: 'Form: field picker' },
  { label: 'ColumnSelector', type: 'class', detail: 'Data: column picker' },
  { label: 'FileManager', type: 'class', detail: 'File: file browser' },
  { label: 'MenuRenderer', type: 'class', detail: 'Menu: render menu tree' },
  { label: 'PermissionGate', type: 'class', detail: 'Permission: conditional render' },
  { label: 'PermissionManager', type: 'class', detail: 'Permission: manager UI' },
  { label: 'Widget', type: 'class', detail: 'Extension: embed widget by ID' },
  { label: 'WebSocketManager', type: 'class', detail: 'WebSocket: connection manager' },
  { label: 'UButton', type: 'class', detail: 'Nuxt UI: button' },
  { label: 'UCard', type: 'class', detail: 'Nuxt UI: card' },
  { label: 'UInput', type: 'class', detail: 'Nuxt UI: input' },
  { label: 'UTable', type: 'class', detail: 'Nuxt UI: table' },
  { label: 'UBadge', type: 'class', detail: 'Nuxt UI: badge' },
  { label: 'USelect', type: 'class', detail: 'Nuxt UI: select' },
  { label: 'UTextarea', type: 'class', detail: 'Nuxt UI: textarea' },
  { label: 'USwitch', type: 'class', detail: 'Nuxt UI: switch toggle' },
  { label: 'UForm', type: 'class', detail: 'Nuxt UI: form wrapper' },
  { label: 'UFormField', type: 'class', detail: 'Nuxt UI: form field' },
];
