export const ENFYRA_COMPLETIONS = [
  { label: '@BODY', type: 'variable', detail: 'Request body ($ctx.$body)' },
  { label: '@QUERY', type: 'variable', detail: 'Query params ($ctx.$query)' },
  { label: '@PARAMS', type: 'variable', detail: 'Route params ($ctx.$params)' },
  { label: '@USER', type: 'variable', detail: 'Current user ($ctx.$user)' },
  { label: '@HELPERS', type: 'variable', detail: 'Helpers: $jwt, $bcrypt, autoSlug' },
  { label: '@SOCKET', type: 'variable', detail: 'WebSocket helper ($ctx.$socket)' },
  { label: '@FETCH', type: 'function', detail: 'Safe fetch helper ($ctx.$helpers.$fetch)' },
  { label: '@DATA', type: 'variable', detail: 'Response data (post-hooks)' },
  { label: '@STATUS', type: 'variable', detail: 'Status code (post-hooks)' },
  { label: '@FLOW_PAYLOAD', type: 'variable', detail: 'Flow input payload' },
  { label: '@FLOW_LAST', type: 'variable', detail: 'Last step result' },
  { label: '@FLOW', type: 'variable', detail: 'Flow data chain' },
  { label: '@FLOW_META', type: 'variable', detail: 'Flow metadata (flowId, flowName)' },
  { label: '@DISPATCH', type: 'variable', detail: 'Flow trigger service' },
  { label: '@DISPATCH.trigger', type: 'function', detail: 'Trigger another flow' },
  { label: '@REPOS', type: 'variable', detail: 'All repositories' },
  { label: '@THROW400', type: 'function', detail: 'Throw Bad Request' },
  { label: '@THROW401', type: 'function', detail: 'Throw Unauthorized' },
  { label: '@THROW403', type: 'function', detail: 'Throw Forbidden' },
  { label: '@THROW404', type: 'function', detail: 'Throw Not Found' },
  { label: '@THROW500', type: 'function', detail: 'Throw Internal Error' },
];

export const ENFYRA_METHOD_COMPLETIONS = [
  { label: '.find', type: 'method', detail: '({ filter, fields, limit, sort })' },
  { label: '.findOne', type: 'method', detail: '({ filter, fields })' },
  { label: '.create', type: 'method', detail: '({ data })' },
  { label: '.update', type: 'method', detail: '({ id, data })' },
  { label: '.delete', type: 'method', detail: '({ id })' },
  { label: '.count', type: 'method', detail: '({ filter })' },
  { label: '.aggregate', type: 'method', detail: '({ aggregate })' },
];

export const VUE_COMPLETIONS = [
  { label: 'ref', type: 'function', detail: 'Reactive reference' },
  { label: 'reactive', type: 'function', detail: 'Reactive object' },
  { label: 'computed', type: 'function', detail: 'Computed property' },
  { label: 'readonly', type: 'function', detail: 'Readonly proxy' },
  { label: 'shallowRef', type: 'function', detail: 'Shallow reactive ref' },
  { label: 'shallowReactive', type: 'function', detail: 'Shallow reactive object' },
  { label: 'watch', type: 'function', detail: 'Watch reactive source' },
  { label: 'watchEffect', type: 'function', detail: 'Auto-tracking effect' },
  { label: 'onMounted', type: 'function', detail: 'Lifecycle: mounted' },
  { label: 'onUnmounted', type: 'function', detail: 'Lifecycle: unmounted' },
  { label: 'onBeforeMount', type: 'function', detail: 'Lifecycle: before mount' },
  { label: 'onBeforeUnmount', type: 'function', detail: 'Lifecycle: before unmount' },
  { label: 'onUpdated', type: 'function', detail: 'Lifecycle: updated' },
  { label: 'nextTick', type: 'function', detail: 'Next DOM update' },
  { label: 'defineProps', type: 'function', detail: 'Declare props' },
  { label: 'defineEmits', type: 'function', detail: 'Declare emits' },
  { label: 'defineExpose', type: 'function', detail: 'Expose to parent' },
  { label: 'resolveComponent', type: 'function', detail: 'Resolve dynamic component' },
  { label: 'h', type: 'function', detail: 'Create VNode' },
  { label: 'toRef', type: 'function', detail: 'Property to ref' },
  { label: 'toRefs', type: 'function', detail: 'Object to refs' },
  { label: 'unref', type: 'function', detail: 'Unwrap ref value' },
  { label: 'isRef', type: 'function', detail: 'Check if ref' },
  { label: 'toRaw', type: 'function', detail: 'Get raw object' },
  { label: 'markRaw', type: 'function', detail: 'Mark non-reactive' },
  { label: 'useRoute', type: 'function', detail: 'Nuxt: current route' },
  { label: 'useRouter', type: 'function', detail: 'Nuxt: router instance' },
  { label: 'navigateTo', type: 'function', detail: 'Nuxt: navigate' },
  { label: 'useState', type: 'function', detail: 'Nuxt: shared state' },
  { label: 'useCookie', type: 'function', detail: 'Nuxt: cookie ref' },
  { label: 'useNuxtApp', type: 'function', detail: 'Nuxt: app instance' },
  { label: 'useRuntimeConfig', type: 'function', detail: 'Nuxt: runtime config' },
  { label: 'useFetch', type: 'function', detail: 'Nuxt: fetch data' },
  { label: 'useAsyncData', type: 'function', detail: 'Nuxt: async data' },
  { label: 'useLazyFetch', type: 'function', detail: 'Nuxt: lazy fetch' },
  { label: 'useHead', type: 'function', detail: 'Nuxt: head meta' },
  { label: 'useToast', type: 'function', detail: 'Nuxt UI: toast notifications' },
  { label: 'useApi', type: 'function', detail: 'Enfyra: API client { data, execute, error, pending }' },
  { label: 'useAuth', type: 'function', detail: 'Enfyra: { me, login, logout, isLoggedIn }' },
  { label: 'usePermissions', type: 'function', detail: 'Enfyra: { hasPermission, checkPermissionCondition }' },
  { label: 'useSchema', type: 'function', detail: 'Enfyra: { schemas, fetchSchema, definition, editableFields, generateEmptyForm }' },
  { label: 'useGlobalState', type: 'function', detail: 'Enfyra: { settings, storageConfigs, sidebarVisible }' },
  { label: 'useScreen', type: 'function', detail: 'Enfyra: { isMobile, isTablet, isDesktop, width, height }' },
  { label: 'useConfirm', type: 'function', detail: 'Enfyra: { confirm({ title, content }) }' },
  { label: 'useHeaderActionRegistry', type: 'function', detail: 'Enfyra: register header actions' },
  { label: 'useSubHeaderActionRegistry', type: 'function', detail: 'Enfyra: register sub-header actions' },
  { label: 'useMenuRegistry', type: 'function', detail: 'Enfyra: { menuItems, registerMenuItem }' },
  { label: 'useFilterQuery', type: 'function', detail: 'Enfyra: { buildQuery, createEmptyFilter }' },
  { label: 'useDatabase', type: 'function', detail: 'Enfyra: { getId, getIdFieldName }' },
  { label: 'useRoutes', type: 'function', detail: 'Enfyra: route management' },
  { label: 'useHighlight', type: 'function', detail: 'Enfyra: code highlighting' },
  { label: 'useMounted', type: 'function', detail: 'Enfyra: { isMounted }' },
];

export const VUE_COMPONENT_COMPLETIONS = [
  { label: 'EmptyState', type: 'class', detail: 'Common: empty state display' },
  { label: 'LoadingState', type: 'class', detail: 'Common: loading indicator' },
  { label: 'ErrorState', type: 'class', detail: 'Common: error display' },
  { label: 'PageHeader', type: 'class', detail: 'Common: page header' },
  { label: 'FormCard', type: 'class', detail: 'Common: form container' },
  { label: 'Modal', type: 'class', detail: 'Common: modal dialog' },
  { label: 'Drawer', type: 'class', detail: 'Common: slide drawer' },
  { label: 'DataTable', type: 'class', detail: 'Data: sortable table' },
  { label: 'DataTableLazy', type: 'class', detail: 'Data: lazy-loaded table' },
  { label: 'FormEditor', type: 'class', detail: 'Form: metadata-driven editor' },
  { label: 'FilterEditor', type: 'class', detail: 'Form: filter builder' },
  { label: 'FieldSelector', type: 'class', detail: 'Form: field picker' },
  { label: 'ColumnSelector', type: 'class', detail: 'Data: column picker' },
  { label: 'FileManager', type: 'class', detail: 'File: file browser' },
  { label: 'MenuRenderer', type: 'class', detail: 'Menu: render menu tree' },
  { label: 'PermissionGate', type: 'class', detail: 'Permission: conditional render' },
  { label: 'PermissionManager', type: 'class', detail: 'Permission: manager UI' },
  { label: 'Widget', type: 'class', detail: 'Extension: embed widget by ID' },
  { label: 'WebSocketManager', type: 'class', detail: 'WebSocket: connection manager' },
  { label: 'UButton', type: 'class', detail: 'Nuxt UI: button' },
  { label: 'UCard', type: 'class', detail: 'Nuxt UI: card' },
  { label: 'UInput', type: 'class', detail: 'Nuxt UI: input' },
  { label: 'UTable', type: 'class', detail: 'Nuxt UI: table' },
  { label: 'UBadge', type: 'class', detail: 'Nuxt UI: badge' },
  { label: 'USelect', type: 'class', detail: 'Nuxt UI: select' },
  { label: 'UTextarea', type: 'class', detail: 'Nuxt UI: textarea' },
  { label: 'USwitch', type: 'class', detail: 'Nuxt UI: switch toggle' },
  { label: 'UForm', type: 'class', detail: 'Nuxt UI: form wrapper' },
  { label: 'UFormField', type: 'class', detail: 'Nuxt UI: form field' },
];
